### ISSUE TITLE
Elasticdump for wikidata dump takes a long time

### ISSUE THREAD

**Issue by jeremytanjianle** [SDM-TIB/falcon2.0#10]
Hi, I've followed the instructions to use elasticdump to place the wikidata into elasticsearch. However, elasticdump has been running for a long time. 

- Is there an estimate on how long will it take for the 9gb of data for just the entities?
- Is there a smaller dataset that I can try this on?

Thanks.

**Comment by AhmadSakor** [comment]
Hi
thanks for your interest in our project.
It takes some hours to be fully uploaded since the number of instances is relatively high.
Providing a smaller dataset would affects the quality of recognition and linking. However, we are going to release soon a new version of Falcon2.0 background knowledge where we have the latest version of Wikidata and we removed a lot of noise from the BK. So It would be smaller and take less time to be uploaded.

So I would suggest to wait for the new version

Thanks

**Comment by jeremytanjianle** [comment]
Thanks for the prompt reply. Excited to see the new version of background knowledge. 

While using Wikidump, I constantly receive out of memory errors from node.js, even after I increase the ndoe size to 8192. 

Please let me know if there were required pre-set settings that are required for the wikidump step, thank you.

**Comment by AhmadSakor** [comment]
I faced a similar problem recently
you have to upgrade elasticdump and nodejs to the latest version then it should work

**Comment by cdhx** [comment]
Hi, the wikidump you provide in github is still 9GB, it seems not become smaller?

I find wikidataentity.json has 48M line while my elastic search takes 7 minutes to  import 40k docs. It seems import 9GB will takes 7 days. 

Do you know why my import speed is different from yours (you only take several hour)

Any help would be appreciate!   
```
Sun，18 Jun 2023 03:23:06 GMT | got 100 objects from source file (offset: 0)
Sun，18 Jun 2023 03:23:06 GMT | sent 100 objects to destination elasticsearch，wrote 100
....
Sun，18 Jun 2023 03:31:12 GMT | got 100 objects from source file (offset: 48600)
Sun，18 Jun 2023 03:31:12 GMT | sent 100 objects to destination elasticsearch，wrote 100
```

I have already set jvm.option to 16G
```
-Xms16g
-Xmx16g
```

**Comment by cdhx** [comment]
I have already set jvm.option to 16G

```
-Xms16g
-Xmx16g
```
